// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureScreenBase64() {
  return window['go']['main']['App']['CaptureScreenBase64']();
}

export function DeleteTemplate(arg1) {
  return window['go']['main']['App']['DeleteTemplate'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTemplateThumbnailBase64(arg1) {
  return window['go']['main']['App']['GetTemplateThumbnailBase64'](arg1);
}

export function ImportTemplate(arg1, arg2) {
  return window['go']['main']['App']['ImportTemplate'](arg1, arg2);
}

export function ListTemplates() {
  return window['go']['main']['App']['ListTemplates']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveTemplate(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveTemplate'](arg1, arg2, arg3);
}

export function StartMonitoring(arg1, arg2) {
  return window['go']['main']['App']['StartMonitoring'](arg1, arg2);
}

export function StopMonitoring() {
  return window['go']['main']['App']['StopMonitoring']();
}

export function TestMatch() {
  return window['go']['main']['App']['TestMatch']();
}

export function UpdateTemplate(arg1) {
  return window['go']['main']['App']['UpdateTemplate'](arg1);
}
