// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CaptureScreenBase64():Promise<string>;

export function DeleteTemplate(arg1:string):Promise<void>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetSettings():Promise<main.AppSettings>;

export function GetStatus():Promise<main.MonitorStatus>;

export function GetTemplateThumbnailBase64(arg1:string):Promise<string>;

export function ImportTemplate(arg1:string, arg2:number):Promise<main.TemplateItem>;

export function ListTemplates():Promise<Array<main.TemplateItem>>;

export function QuitApp():Promise<void>;

export function SaveSettings(arg1:main.AppSettings):Promise<void>;

export function SaveTemplate(arg1:string, arg2:string, arg3:number):Promise<main.TemplateItem>;

export function StartMonitoring(arg1:string, arg2:main.AppSettings):Promise<void>;

export function StopMonitoring():Promise<void>;

export function TestMatch():Promise<Array<main.MatchScore>>;

export function UpdateTemplate(arg1:main.TemplateItem):Promise<void>;
